/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package alcoholicosidentificados;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @authors
 *          Anabel Gómez Ríos
 *          Gustavo Rivas Gervilla
 *          Luis Suárez Lloréns
 *          Jacinto Carrasco Castillo
 */
public class JD_Inicial extends javax.swing.JDialog {
    
    private Sistema sistema;
    private Interfaz interfaz;
    private JD_RegistrarConsumidor reg_cons;
    private JD_RegistrarEmpresa reg_emp;
    private Funcionalidad f;
    
    /**
     * Creates new form VentanaPrincipal
     */
    public JD_Inicial(java.awt.Frame parent, boolean modal,Sistema sist) {
        super(parent, modal);
        initComponents();
        reg_cons=new JD_RegistrarConsumidor(parent,true,sist);
        reg_emp=new JD_RegistrarEmpresa(parent,true,sist);
        f=new Funcionalidad();
        f.conectar();
        sistema=sist;
        this.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e){
                System.exit(0);
            }
        });
    }
    
    public void mostrar(String args[]) {
    }
    
    public Interfaz getInterfaz(){
        this.setVisible(true);
        return interfaz;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonRegConsumidor = new javax.swing.JButton();
        botonAdmin = new javax.swing.JButton();
        textIdentificador = new javax.swing.JTextField();
        labelIdentificador = new javax.swing.JLabel();
        labelContraseña = new javax.swing.JLabel();
        botonEntrar = new javax.swing.JButton();
        botonRegEmpresa = new javax.swing.JButton();
        textContrasena = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        botonRegConsumidor.setText("Registrar Consumidor");
        botonRegConsumidor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegConsumidorActionPerformed(evt);
            }
        });

        botonAdmin.setText("Administrador");
        botonAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAdminActionPerformed(evt);
            }
        });

        labelIdentificador.setText("Identificador");

        labelContraseña.setText("Contraseña");

        botonEntrar.setText("Entrar");
        botonEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEntrarActionPerformed(evt);
            }
        });

        botonRegEmpresa.setText("Registrar Empresa");
        botonRegEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegEmpresaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelContraseña)
                    .addComponent(labelIdentificador))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(textIdentificador, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                    .addComponent(textContrasena))
                .addGap(69, 69, 69))
            .addGroup(layout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addComponent(botonEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botonAdmin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botonRegConsumidor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonRegEmpresa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelIdentificador)
                    .addComponent(textIdentificador, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelContraseña)
                    .addComponent(textContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(botonEntrar)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                        .addComponent(botonRegConsumidor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botonRegEmpresa)
                            .addComponent(botonAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAdminActionPerformed
           interfaz=Interfaz.I_ADMINISTRADOR;
           this.dispose();
    }//GEN-LAST:event_botonAdminActionPerformed

    private void botonRegConsumidorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegConsumidorActionPerformed
        String idCons=reg_cons.getIdUsuario();
        interfaz=Interfaz.I_CONSUMIDOR;
        sistema.setIdActivo(idCons);
        this.dispose();
    }//GEN-LAST:event_botonRegConsumidorActionPerformed

    private void botonEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEntrarActionPerformed
        String consulta;
        String idUsuario=textIdentificador.getText();
        String contrasena=new String(textContrasena.getPassword());
        
        consulta="SELECT * FROM Usuario WHERE IdUsuario='"+idUsuario+"' AND Contraseña='"+contrasena+"'";
        ResultSet r=f.consultar(consulta);
        try {
            if(r.next()){
                r=f.consultar("SELECT * FROM Consumidor WHERE idUsuario='"+idUsuario+"'");
                
                if(r.next())
                    interfaz=Interfaz.I_CONSUMIDOR;
                else
                    interfaz=Interfaz.I_EMPRESA;
                
                sistema.setIdActivo(idUsuario);
                this.dispose();
            }
        } catch (SQLException ex) {
            Logger.getLogger(JD_Inicial.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_botonEntrarActionPerformed

    private void botonRegEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegEmpresaActionPerformed
        String idEmpresa=reg_emp.getIdUsuario();
        interfaz=Interfaz.I_EMPRESA;
        sistema.setIdActivo(idEmpresa);
        this.dispose();
    }//GEN-LAST:event_botonRegEmpresaActionPerformed

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAdmin;
    private javax.swing.JButton botonEntrar;
    private javax.swing.JButton botonRegConsumidor;
    private javax.swing.JButton botonRegEmpresa;
    private javax.swing.JLabel labelContraseña;
    private javax.swing.JLabel labelIdentificador;
    private javax.swing.JPasswordField textContrasena;
    private javax.swing.JTextField textIdentificador;
    // End of variables declaration//GEN-END:variables
}
