/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package alcoholicosidentificados;

import java.util.ArrayList;

/**
 *
 * @authors
 *          Anabel Gómez Ríos
 *          Gustavo Rivas Gervilla
 *          Luis Suárez Lloréns
 *          Jacinto Carrasco Castillo
 */
public class JD_RegistrarConsumidor extends javax.swing.JDialog {
    
    private String idUsuario;
    private final Funcionalidad f;
    private final Sistema sist;
    
    /**
     * Creates new form VentanaPrincipal
     * @param parent
     * @param modal
     * @param sist
     */
    public JD_RegistrarConsumidor(java.awt.Frame parent, boolean modal,Sistema sist) {
        super(parent, modal);
        initComponents();
        this.sist=sist;
        f=new Funcionalidad();
        f.conectar();
        
        this.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e){
                System.exit(0);
            }
        });
    }
    
    public void mostrar(String args[]) {
    }
    
    public String getIdUsuario(){
        this.setVisible(true);
        return idUsuario;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textDireccion = new javax.swing.JTextField();
        textNombre = new javax.swing.JTextField();
        labelIdentificador = new javax.swing.JLabel();
        labelNombre = new javax.swing.JLabel();
        textIdentificador = new javax.swing.JTextField();
        textContrasena = new javax.swing.JTextField();
        labelDireccion = new javax.swing.JLabel();
        labelContrasena = new javax.swing.JLabel();
        textFechaNacimiento = new javax.swing.JTextField();
        textApellidos = new javax.swing.JTextField();
        labelFechaNacimiento = new javax.swing.JLabel();
        labelApellidos = new javax.swing.JLabel();
        botonRegistrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        labelIdentificador.setText("Identificador*");

        labelNombre.setText("Nombre");

        labelDireccion.setText("Direccion");

        labelContrasena.setText("Contraseña*");

        textFechaNacimiento.setText("DD/MM/YYYY");

        labelFechaNacimiento.setText("Fecha Nacimiento*");

        labelApellidos.setText("Apellidos");

        botonRegistrar.setText("Registrar");
        botonRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegistrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelIdentificador)
                            .addComponent(labelNombre)
                            .addComponent(labelContrasena)
                            .addComponent(labelDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textIdentificador, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textNombre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textContrasena, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textDireccion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelApellidos)
                            .addComponent(labelFechaNacimiento))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textApellidos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textFechaNacimiento, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(botonRegistrar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelIdentificador)
                    .addComponent(textIdentificador, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNombre))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelContrasena))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelDireccion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelApellidos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelFechaNacimiento))
                .addGap(26, 26, 26)
                .addComponent(botonRegistrar)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegistrarActionPerformed
        String contrasena=textContrasena.getText();
        String nombre=textNombre.getText();
        String direccion=textDireccion.getText();
        String apellidos=textApellidos.getText();
        String fecha=textFechaNacimiento.getText();
        
        ArrayList<String> valores=new ArrayList();
        ArrayList<String> argumentos=new ArrayList();
        
        if(textIdentificador.getText().length()>0 && contrasena.length()>0 && fecha.length()>0){
            valores.add(textIdentificador.getText());
            valores.add(contrasena);
            
            if(nombre.length()>0){
                argumentos.add("NOMBRE");
                valores.add(nombre);
            }
            if(direccion.length()>0){
                argumentos.add("DIRECCION");
                valores.add(direccion);
            }
            
            sist.registrarUsuario(argumentos, valores);
            valores.clear();
            
            valores.add(textIdentificador.getText());
            valores.add(fecha);
            
            if(apellidos.length()>0){
                valores.add(apellidos);
            }
            
            sist.registrarConsumidor(valores);
            
            idUsuario=textIdentificador.getText();
            this.dispose();
        }
    }//GEN-LAST:event_botonRegistrarActionPerformed

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonRegistrar;
    private javax.swing.JLabel labelApellidos;
    private javax.swing.JLabel labelContrasena;
    private javax.swing.JLabel labelDireccion;
    private javax.swing.JLabel labelFechaNacimiento;
    private javax.swing.JLabel labelIdentificador;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JTextField textApellidos;
    private javax.swing.JTextField textContrasena;
    private javax.swing.JTextField textDireccion;
    private javax.swing.JTextField textFechaNacimiento;
    private javax.swing.JTextField textIdentificador;
    private javax.swing.JTextField textNombre;
    // End of variables declaration//GEN-END:variables
}
